"""add group_name team_name role_note

Revision ID: 84d691b91602
Revises: 
Create Date: 2026-02-08 22:21:57.224889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d691b91602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('team_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('role_note', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('role_note')
        batch_op.drop_column('team_name')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
